/*
 * This file was generated by the Gradle 'init' task.
 */

tasks.getByName("bootJar") {
    enabled = true
}

tasks.getByName("jar") {
    enabled = false
}

plugins {
    id("com.adevspoon.kotlin-common-conventions")
}

dependencies {
    implementation(project(":adevspoon-common"))
    implementation(project(":adevspoon-domain"))
    implementation(project(":adevspoon-infrastructure"))
}

tasks.register("copyConfig", Copy::class) {
    copy {
        from("../adevspoon-config/backend/batch")
        include("*.yml", "*.xml")
        into("src/main/resources")
    }
}