/*
 * This file was generated by the Gradle 'init' task.
 */

tasks.getByName("bootJar") {
    enabled = false
}

tasks.getByName("jar") {
    enabled = true
}

tasks.register("copyConfig", Copy::class) {
    copy {
        from("../adevspoon-config/backend/common")
        include("*.yml", "*.xml")
        into("src/main/resources")
    }
}

plugins {
    id("com.adevspoon.kotlin-common-conventions")
}

dependencies {}

