/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.adevspoon.kotlin-common-conventions")
}

dependencies {
    implementation("io.jsonwebtoken:jjwt-api:0.11.5")
    runtimeOnly("io.jsonwebtoken:jjwt-impl:0.11.5")
    runtimeOnly("io.jsonwebtoken:jjwt-jackson:0.11.5")
}