spring:
  profiles:
    default: local
    group:
      local:
        - domain-local
        - common-local
        - infrastructure
#      dev:
#        - infrastructure-dev
#        - domain-dev
#        - logging
#        - metrics
#      prod:
#        - infrastructure-prod
#        - domain-prod
#        - common-prod
#        - metrics

---
spring:
  config:
    activate:
      on-profile: local, dev
  docker:
    compose:
      lifecycle-management: start_only
      file: ./adevspoon-api/docker-compose-local.yml
      enabled: true

springdoc:
  swagger-ui:
    path: /docs



