spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B # 파일을 디스크에 저장하지 않고 메모리에 저장하는 최소 크기 (default: 0B)
      location: /Users/rokwon/Downloads/image-temp # 업로드된 파일이 임시로 저장되는 디스크 위치 (default: WAS가 결정)
      max-file-size: 10MB
      max-request-size: 10MB
  docker:
    compose:
      lifecycle-management: start_only
      file: ./adevspoon-api/docker-compose-local.yml
      enabled: true

jwt:
  secretKey: qwertyuiop1234567890asdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM
  access-expiration-hours: 876000
  refresh-expiration-hours: 876000
  issuer: adevspoon

custom:
  image:
    temp-dir: /Users/rokwon/Downloads/image-temp