spring:
  profiles:
    default: local
    group:
      local:
        - api-local
        - domain-local
        - common-local
        - infrastructure-local
      dev:
        - api-dev
        - common-dev
        - domain-dev
        - infrastructure-dev
      prod:
        - api-prod
        - common-prod
        - domain-prod
        - infrastructure-prod

server:
  servlet:
    context-path: /api
  shutdown: graceful

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
    tags-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-order-by-keys: true