spring:
  profiles:
    active: local
    include:
      - infrastructure
      - domain

  docker:
    compose:
      lifecycle-management: start_only
      file: ./adevspoon-api/docker-compose-local.yml
      enabled: true
---
spring:
  profiles:
    active: dev