spring:
  profiles:
    default: local
    group:
      local:
        - api-local
        - domain-local
        - common-local
        - infrastructure-local
      dev:
        - api-dev
        - common-dev
        - domain-dev
        - infrastructure-dev
      prod:
        - api-prod
        - common-prod
        - domain-prod
        - infrastructure-prod

server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /docs