package com.adevspoon.domain

import org.springframework.boot.autoconfigure.SpringBootApplication
import org.springframework.boot.context.properties.ConfigurationPropertiesScan


@ConfigurationPropertiesScan
@SpringBootApplication
class AdevspoonDomain