spring:
  profiles:
    default: prod
    group:
      local-docker:
        - batch-local-docker
      local:
        - batch-local
      dev:
        - batch-dev
      prod:
        - batch-prod

server:
  shutdown: graceful
