/*
 * This file was generated by the Gradle 'init' task.
 */

tasks.getByName("bootJar") {
    enabled = false
}

tasks.getByName("jar") {
    enabled = true
}

plugins {
    id("com.adevspoon.kotlin-common-conventions")
}

dependencies { }