feign:
  kakao:
    url: https://kapi.kakao.com
  apple:
    url: https://appleid.apple.com

cloud:
  aws:
    region:
      static: us-east-1
    s3:
      bucket: test-bucket
    stack:
      auto: false