version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ec2-user/adevspoon
    overwrite: yes

permissions:
  - object: /
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60