version: '3'
services:
  mysql:
    image: mysql:8.0.33
    container_name: adevspoon-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: adevspoon-local
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /Users/rokwon/private/docker-volume:/var/lib/mysql
