package com.adevspoon.domain.techQuestion.exception

import com.adevspoon.common.exception.AdevspoonException


class QuestionNotOpenedException : AdevspoonException(QuestionDomainErrorCode.QUESTION_NOT_OPENED)
class QuestionExhaustedException : AdevspoonException(QuestionDomainErrorCode.QUESTION_EXHAUSTED)
class QuestionAnswerReportNotAllowedException : AdevspoonException(QuestionDomainErrorCode.QUESTION_ANSWER_REPORT_NOT_ALLOWED)
class QuestionAnswerReportAlreadyExistException : AdevspoonException(QuestionDomainErrorCode.QUESTION_ANSWER_REPORT_ALREADY_EXIST)

class QuestionAnswerEditUnauthorizedException : AdevspoonException(QuestionDomainErrorCode.QUESTION_ANSWER_EDIT_UNAUTHORIZED)

class QuestionNotFoundException : AdevspoonException(QuestionDomainErrorCode.QUESTION_NOT_FOUND)
class QuestionCategoryNotFoundException : AdevspoonException(QuestionDomainErrorCode.QUESTION_CATEGORY_NOT_FOUND)
class QuestionAnswerNotFoundException : AdevspoonException(QuestionDomainErrorCode.QUESTION_ANSWER_NOT_FOUND)
class QuestionNotIssuedException : AdevspoonException(QuestionDomainErrorCode.QUESTION_NOT_ISSUED)

class QuestionAnswerInvalidReturnException : AdevspoonException(QuestionDomainErrorCode.QUESTION_ANSWER_INVALID_RETURN)

class NegativeLikeCountExceptionForTechQuestion(type: String, contentId: Long) : AdevspoonException(
    QuestionDomainErrorCode.MINIMUM_LIKE_COUNT,
    detailReason = QuestionDomainErrorCode.MINIMUM_LIKE_COUNT.message + " type: $type, id: $contentId"
)
